spring.application.name=demo
# Enable H2 console
# Use H2 in-memory database
spring.datasource.url=jdbc:h2:file:/home/jeev/test;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=TRUE;MODE=MYSQL
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=create-drop


# Automatically create/update tables based on your JPA entities
# spring.jpa.hibernate.ddl-auto=update

# Enable the H2 web console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
